### PR TITLE
feat: headless selects

### PR DESCRIPTION
**Pull request by anamontiaga**
Single and multiple select following Listbox Headless UI component.

Before merging, delete the previous selects and replace with these ones.

[Issue #79](https://github.com/Vizzuality/front-end-scaffold/issues/79)

### CODE REVIEW

**Review by mbarrenechea — APPROVED** [review]
I saw that the multiselect loses the focus if you try to use the keyboard. That means that the accessibility is not ok. We need to review a little bit. I'm ok if we merge it as it is and we can make those changes/improvements later. It will be better than the current ones

**Review by mbarrenechea — APPROVED** [review]

**Review by andresgnlez — APPROVED** [review]
Overall, it looks good. Just a little thing: I toggled the "disabled" control but I don't see any visual change in the selector that indicates is disabled. I had to move the mouse over the component and click to verify it.

image

**Comment by mbarrenechea** [comment]
> 

You checked the wrong ones, but it's ok...

**Comment by mbarrenechea** [comment]
> Overall, it looks good. Just a little thing: I toggled the "disabled" control but I don't see any visual change in the selector that indicates is disabled. I had to move the mouse over the component and click to verify it.
> 
> image

You checked the wrong ones. I removed the old ones so you don't get confused this time

**Pull request merged**
