### PR TITLE
Added prettier integration with eslint

### PR DESCRIPTION
**Pull request by davidsingal**
We may have to add more options in the prettier configuration file.  For now, you can see the prettier removes al `;` at the end of every line.

Please, let me know what do you think? 

@pablopareja it should fix your issue in your editor as well

### CODE REVIEW

**Review by mbarrenechea — APPROVED** [review]
TBH, I feel uncomfortable about removing the `;` but it may be related to the fact that I'm a boomer. Nice work.

Fix the conflicts before merging

**Comment by davidsingal** [comment]
@pablopareja your review is required xD

**Comment by davidsingal** [comment]
@mbarrenechea I've added the rule for semicolons. I also like the semicolons

**Review by pablopareja — APPROVED** [review]
Everything seems to work fine for me too 👍

**Pull request merged**
